//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pageage_printer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class RemoteCNC_config : global::System.Configuration.ApplicationSettingsBase {
        
        private static RemoteCNC_config defaultInstance = ((RemoteCNC_config)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RemoteCNC_config())));
        
        public static RemoteCNC_config Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.31.250")]
        public string database_ip {
            get {
                return ((string)(this["database_ip"]));
            }
            set {
                this["database_ip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chk")]
        public string database_user {
            get {
                return ((string)(this["database_user"]));
            }
            set {
                this["database_user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12345678")]
        public string database_pass {
            get {
                return ((string)(this["database_pass"]));
            }
            set {
                this["database_pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cnc {
            get {
                return ((bool)(this["cnc"]));
            }
            set {
                this["cnc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pakage1 {
            get {
                return ((bool)(this["pakage1"]));
            }
            set {
                this["pakage1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hanhai_manufacture")]
        public string database_name {
            get {
                return ((string)(this["database_name"]));
            }
            set {
                this["database_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("瀚海")]
        public string Factory {
            get {
                return ((string)(this["Factory"]));
            }
            set {
                this["Factory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("work_cnc_task_list")]
        public string sheet_cnc_task {
            get {
                return ((string)(this["sheet_cnc_task"]));
            }
            set {
                this["sheet_cnc_task"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("order_element_online")]
        public string sheet_element {
            get {
                return ((string)(this["sheet_element"]));
            }
            set {
                this["sheet_element"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("order_contract_internal")]
        public string sheet_contract {
            get {
                return ((string)(this["sheet_contract"]));
            }
            set {
                this["sheet_contract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gprinter GP-9025T")]
        public string name_printer {
            get {
                return ((string)(this["name_printer"]));
            }
            set {
                this["name_printer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Print_Barcode {
            get {
                return ((string)(this["Print_Barcode"]));
            }
            set {
                this["Print_Barcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pakage2 {
            get {
                return ((bool)(this["pakage2"]));
            }
            set {
                this["pakage2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string choose_state {
            get {
                return ((string)(this["choose_state"]));
            }
            set {
                this["choose_state"] = value;
            }
        }
    }
}
